# Jour 1 : Introduction à Pandas et Analyse Exploratoire des Données (EDA)

## Documentations
- [Pandas](https://pandas.pydata.org/pandas-docs/stable/)
- [Matplotlib](https://matplotlib.org/stable/users/index.html)


## 1. Bases de Pandas
> Préparez votre IDE pour une version de Python `>=3.11` et installez `pandas`,`pandas-stubs`, `openpyxl` et `matplotlib`.

In [20]:
!python --version

Python 3.13.0

In [21]:
!pip install pandas pandas-stubs openpyxl matplotlib

Requirement already satisfied: pandas in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (3.0.6)
Requirement already satisfied: pandas-stubs in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (3.0.5.260914)
Requirement already satisfied: openpyxl in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (3.11.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: et-xmlfile in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from matplotlib) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: six>=1.5 in c:\users\admin stagiaire\pycharmprojects\cc6-python-ind\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

> Configurez `pandas` afin que l'affichage par défaut des DataFrames affiche au
minimum 6 colonnes, au maximum 12 colonnes, au maximum 100 lignes de
contenu, au maximum 20 caractères par colonne et 240 caractères par ligne.

In [40]:
import pandas as pd
import numpy as np
# Colonnes (min 6, max 12) avec 20 caractères max pour chaque
pd.set_option('display.max_columns', 12)    # 12 colonnes max
pd.set_option('display.max_colwidth', 20)   # 20 caractères par colonne

# Lignes (max 100 lignes) avec 240 caractères max par ligne
pd.set_option('display.max_rows', 100)      # 100 lignes max
pd.set_option('display.width', 240)         # 240 caractères par ligne


# Vérifier que les modifications ont bien été prises en compte
values = ['max_columns', 'max_colwidth', 'max_rows', 'width']
for value in values:
  print(f"{value}: {pd.get_option('display.' + value)}")

max_columns: 12
max_colwidth: 20
max_rows: 100
width: 240

Il n'existe pas d'option minimal pour les colonnes à afficher, cependant on peut contrôler l'affichage des colonnes via le DataFrame directement

`display.min_columns` n'existe pas

```df[[col1, col2, col3, col4, col5, col6 ]]``` -> on force l'affichage des colonnes sélectionnées, ici 6

> Créez un DataFrame depuis des valeurs aléatoires, avec 20 colonnes et 200
lignes, et vérifiez que son affichage respecte la configuration que vous avez
établie précédemment.

In [23]:
import random, string


# Pour vérifier que la taille maximale des colonnes est respectée, on va créer une fonction créant du texte avec au minimum 20 caractères
def random_text(min_len=20, max_len=30):
    return "".join(random.choice(string.ascii_letters + string.digits) for _ in range(random.randint(min_len, max_len))) 

# Création du DataFrame
df = pd.DataFrame(
    [[random_text() for _ in range(20)] for _ in range(200)],
    columns=[f"col_{i}" for i in range(20)],
)
df

,col_0,col_1,col_2,col_3,col_4,col_5,...,col_14,col_15,col_16,col_17,col_18,col_19
0,MVkxHxc7KL3LKMcW...,6CzshedU9NeFogwJ...,vZMVdHWhZPZhYfPV...,1lVtCrxATPSlf4Ge...,w3M2rYTsYp2opc95...,WyGmyjCirUHXONtZ...,...,1wup0rdt7NhY0mZO...,L6VnmmrP8Yo3WpZf...,GISDefTe0UcGxWdd...,B3b8OzWkgKkEMDjo...,cw5cOnosYyOCBZpA...,Bjv0HGzUNg0nC22u...
1,wfqHbRFY8GLJx7oa...,at7DCG4OTiIeKM3k...,ZcC7WhCTzC5KteEF...,sehJIH7bcyW2vjHx...,d3FWz7b61JHGriqb...,PSRSb5O3zoqBEpYz...,...,WkBK3UWKVsxCAyMa...,Om7CSF41aLMLYWoK...,x91nyFxzQJDW1xXJ...,uEpKB02E28lS9V6O...,sXIbVAiYI7XGDkP3...,akrpJAgnHW4yGQTb...
2,MZ2ca5dkETUBwy3C...,4fSy9wxeH9tISFZ1...,UHszIMGmeEm9saiF...,PLrutKcpuqTRiJJ6...,JQQ7umFX4klw2nKT...,Ju9UOkKPsKAfOsKc...,...,9ldrvmCxVhg1Vd3l...,luTjYmxREcEkW6s6...,v0fbEIMGIHCfjAvL...,BJzbcce9vSPHXYdM...,Rc2L8Qw4McESu9i0...,veGdvhz4Iy7H7FaI...
3,ioZqgULDz3tshjXM...,QbfgXUsZpbSNtTid...,PoryUu4yCoiqQH0S...,fmCGd31JuJsFrUbv...,dHx9RjzkjnFQtd0W...,FkFVmQo3d5khOd0R...,...,B0tpZd9oR9Q7b23g...,o2DqIDLkR533U9Kn...,P5S0fyy6uOuW2E9D...,yvJ8EKOAemraowqp...,J1uMVQgtIrPamdRl...,9f6iAamzh4No7lU0...
4,KYmIlGjnqd7UULQv...,cciK1QbedQ55kuXk...,fWQy13IoqaOuGP2N...,Ga8xSXT0pVUVl1Kx...,e5GarFAmO7rWbgjl...,500EDs1mbRJTOA5Q...,...,j8S2WrMPwHmmaGBZ...,60Mi7YFA29RRuILX...,HABXfWF1nfZvCoxd...,cvsikE0VSHjGaBH1...,2wGWVupABddnSVui...,4KrtJj00Yuu3wE5Z...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,cOY46maYzFh1RNkT...,UBFyVmgdj16soIsu...,ZjIiSXcHuBGwLJFp...,2bUhUo0GLUyHeQGU...,VRnmXFLPvaguqJZ6...,g3Xwhe9eXg9eOAEy...,...,V3AfD6CI4RKeQDMl...,JdtUS6012tZDDsAO...,pwOqtt2hAJpLmhLt...,OMYyuvomtXREYb3u...,en6NlolzRz7cNZXl...,Wwsufg564uelMe4J...
196,77AZApvD5GqMKbDV...,TfSlQo7lx8afqoZF...,biul3UvUnz2sTojD...,dxH0bggp6YTsBfl9...,jWY5AOQeEn8OgAKm...,6DXExpSlpgh6Pa8K...,...,epBnexwJalIFTfPr...,r6G8ZBfiCEs1Nken...,HZ3zUQZJC4Zsl3i6...,Uldl2WvNtvg0g6Mm...,vPBDgE5lHZbK2ecB...,vOib6gx6hGAv6Y2n...
197,L0iNl1RTpgutUF4E...,T2U4LR4N1iJnSyV6...,CocAWqoO6tb6fXzz...,TEFjMInbtwxRPgwK...,U2TE2gt4j782EOB6...,SJToc59UZCynvirX...,...,pGpdlVXcgImgOcqq...,C8KZX5wnvVoB06hR...,ozX6NDfuCirwQ79F...,9RiOptxoJmZCcxQA...,QO0wXRrKtyvta5ZJ...,OtyHkMEYkfG047q3...
198,GIhYxh42bBDILDKy...,KbyPiNTfMREj6XfD...,dMZGXnbwVAXaGCWE...,xQU87TDOs8d9Mur2...,J1C63kgj6Hc0bWnQ...,DqLlRbx8AEdubc0N...,...,Yu20buJTRmoafp94...,IG5NuKu2K2KStgd6...,ODHcgLKRyfngRocf...,nUjBqSTkkqk3DBBU...,pEVncZ9nMkEGRTkr...,xE8s1S2om90HOlXx...
199,IKjuZI1VDeQnKY29...,KRCh6BEfqUFh71yu...,J0nS5YrIgPDebWgA...,Vn9KV3b850a5M614...,Ab3wbqGWtv4M2uzo...,ohDHSQPn0QyQUram...,...,ESI2g5NmjNwUA379...,1sBaLmqyXU5b0ACh...,ZiHE2oAHmyAfEreu...,pJiwjC0ojEBCn32B...,TCPKHWxgfDhr9q6Z...,OpTPai2nK2296jnu...

> Expliquez les concepts de base de Pandas, à savoir les `DataFrames` , les `Series` et les `Index`.

# Dataframes
Un `Dataframe`est un ensemble de `Series` Pandas indexées par une valeur.
C'est un tableau à 2 dimensions composés de lignes et de colonnes permettant de mettre en avant les relations entre les différentes variables du jeu de données.

Il peut contenir plusieurs type comme des nombres, du texte, des dates, etc par colonne comme une feuille Excel.

Chaque clé = nom de colonne

Chaque valeur = Series



# Series
Les `Series` sont des objets correspondants à des tableaux à une seule dimension.
C'est l'équivalent d'une seule colonne (ou ligne) avec un index.

Chaque colone de DataFrame est une Serie et associe à chaque valeur un index.


# Index
L'index est un objet contenant les étiquettes des axes (lignes et colonnes), permet d'identifier chaque ligne/colonnne et sert à aligner les données, faire des jointures etc

On peut voir l'index comme une série de données indentifiant des colonnes ou lignes

## 2. Chargement et exploration des données
> Chargez chaque feuille de calcul du fichier Excel dans des  DataFrame séparés,
> pour des variables nommées respectivement :
> - orders
> - territories
> - sales
> - resellers
> - dates
> - products
> - customers

In [24]:
# Création d'un dictionnaire global
dataframes = {}

# Stockage des noms de variables pour les différents dataframes
names = ['orders', 'territories', 'sales', 'resellers', 'dates', 'products', 'customers']

# Lecture du fichier Excel
sheets = pd.read_excel("datas/CC-AIBD-DataAnalyse-donnees.xlsx", sheet_name=None)

# Pour chaque feuille du fichier, on stocke le dataframe dans le dictionnaire global
for i, (_, df) in enumerate(sheets.items()):
    dataframes[names[i]] = df

# Exemple d'affichage d'un dataframe
dataframes['territories']

    SalesTerritoryKey          Region         Country          Group
0                   1       Northwest   United States  North America
1                   2       Northeast   United States  North America
2                   3         Central   United States  North America
3                   4       Southwest   United States  North America
4                   5       Southeast   United States  North America
5                   6          Canada          Canada  North America
6                   7          France          France         Europe
7                   8         Germany         Germany         Europe
8                   9       Australia       Australia        Pacific
9                  10  United Kingdom  United Kingdom         Europe
10                 11    Corporate HQ    Corporate HQ   Corporate HQ

> - Affichez les cinq premières lignes de chaque  DataFrame et vérifiez-en également les types de colonnes.
> - Affichez des informations de base sur les DataFrame via les méthodes info() et describe() pour obtenir des informations sur la taille, les types de données et les valeurs manquantes dans chaque DataFrame .
> - Si besoin, notez les colonnes qui ont un type qui semble incorrect vis-à-vis de leur usage
---
-> Cf présentation pour voir l'analyse des différents dataframes dans la présentation

> - Affichez des informations de distribution (dispersion) du coût standard des produits du catalogue. Affichez la médiane, l'écart-type et la variance.

Pour faire ça, nous allons utiliser `agg` qui va nous permettre d'appliquer une ou plusieurs fonctions d'aggrégation sur notre DataFrame ou sur un groupby afin de produire un tableau de statistiques

In [25]:
df = dataframes["products"]

stats = df["Standard Cost"].agg(["median", "std", "var"])
stats.index = ["Médiane", "Écart type", "Variance"]

stats

Médiane          204.625100
Écart type       497.076884
Variance      247085.428708
Name: Standard Cost, dtype: float64

> Calculez les mêmes informations, mais cette fois-ci par catégorie de produit (Category)

In [26]:
df = dataframes["products"]

stats = df.groupby("Category")["Standard Cost"].agg(["median", "std", "var"])
stats.columns = ["Médiane", "Écart type", "Variance"]

stats

              Médiane  Écart type       Variance
Category
Accessories   11.2163   13.127986     172.344014
Bikes        713.0798  552.407211  305153.726769
Clothing      26.1763   12.424381     154.365235
Components   187.1571  280.636563   78756.880441

## 3. Nettoyage des données
> Assurez-vous dans tous les `DataFrames` qu'il n'existe aucune cellule laissée vide. Si ce n'est pas le cas, affichez les identifiants des colonnes contenant des valeurs vides. Remplacez également ces valeurs par une valeur de repli si besoin

In [27]:
# Trouver les dataframes dans lesquels au moins une cellule a une valeur manquante
dataframes_with_empty_cell = []
for key, df in dataframes.items():
    if df.isna().any().any() > 0:
        dataframes_with_empty_cell.append(key)

print(dataframes_with_empty_cell)

['sales', 'products']

In [28]:
for df in dataframes_with_empty_cell:
    # On regarde les colonnes avec des valeurs manquantes pour les df trouvés
    print(dataframes[df].isna().sum())

SalesOrderLineKey             0
ResellerKey                   0
CustomerKey                   0
ProductKey                    0
OrderDateKey                  0
DueDateKey                    0
ShipDateKey                2113
SalesTerritoryKey             0
Order Quantity                0
Unit Price                    0
Extended Amount               0
Unit Price Discount Pct       0
Product Standard Cost         0
Total Product Cost            0
Sales Amount                  0
dtype: int64
ProductKey        0
SKU               0
Product           0
Standard Cost     0
Color            56
List Price        0
Model             0
Subcategory       0
Category          0
dtype: int64

Nous trouvons ici 2 colonnes problématiques : 
- `ShipDateKey` dans le dataframe `sales`
- `Color` dans le dataframe `products`

## 3.1.1 - `ShipDateKey` dans le dataframe `sales`

Par rapport à ShipDateKey, on remarque que dans le DataFrame, il y a 3 colonnes pour les dates :
- OrderDate en int64
- DueDateKey en int64
- ShipDateKey en float64 -> Ici le type de la colonne est en float sûrement à cause des valeurs manquantes

Je choisis ici de convertir les données en Int64 pour la colonne ShipDateKey afin de garder le concept de clé en int et en rendant nulle (\<NA\>) les valeurs manquantes que je mettrais à -1 pour les ShipDateKey non définies.

Je convertis en Int64 et pas en int64 car ici la colonne peut avoir des valeurs nulles. Si je garde en int64, vu qu'il y a des valeurs manquantes, la colonne va être convertie en float64.

In [29]:
dataframes['sales'].info()

<class 'pandas.DataFrame'>
RangeIndex: 121253 entries, 0 to 121252
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   SalesOrderLineKey        121253 non-null  int64
 1   ResellerKey              121253 non-null  int64
 2   CustomerKey              121253 non-null  int64
 3   ProductKey               121253 non-null  int64
 4   OrderDateKey             121253 non-null  int64
 5   DueDateKey               121253 non-null  int64
 6   ShipDateKey              119140 non-null  float64
 7   SalesTerritoryKey        121253 non-null  int64
 8   Order Quantity           121253 non-null  int64
 9   Unit Price               121253 non-null  float64
 10  Extended Amount          121253 non-null  float64
 11  Unit Price Discount Pct  121253 non-null  int64
 12  Product Standard Cost    121253 non-null  float64
 13  Total Product Cost       121253 non-null  float64
 14  Sales Amount             121253 non-null  float64
dtypes: float64(6), int64(9)
memory usage: 13.9 MB

In [30]:
dataframes['sales']['ShipDateKey'] = dataframes['sales']['ShipDateKey'].astype("Int64")
dataframes['sales']['ShipDateKey'] = dataframes['sales']['ShipDateKey'].fillna(-1)

## 3.1.2 - `Color` dans le dataframe `products`

Ici, les valeurs nulles sont les couleurs des produits.

Je décide juste de remplacer NA par "Default" pour les couleurs nulles dans mon DataFrame.

In [31]:
dataframes['products'].info()

<class 'pandas.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ProductKey     397 non-null    int64
 1   SKU            397 non-null    str
 2   Product        397 non-null    str
 3   Standard Cost  397 non-null    float64
 4   Color          341 non-null    str
 5   List Price     397 non-null    float64
 6   Model          397 non-null    str
 7   Subcategory    397 non-null    str
 8   Category       397 non-null    str
dtypes: float64(2), int64(1), str(6)
memory usage: 28.0 KB

In [32]:
dataframes['products']['Color'].fillna("Default", inplace=True)

C:\Users\Admin Stagiaire\AppData\Local\Temp\ipykernel_15696\430288213.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataframes['products']['Color'].fillna("Default", inplace=True)

0        Black
1          Red
2          Red
3          Red
4          Red
        ...
392    Default
393    Default
394      Black
395      Black
396      Black
Name: Color, Length: 397, dtype: str

In [33]:
dataframes['products'].info()

<class 'pandas.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ProductKey     397 non-null    int64
 1   SKU            397 non-null    str
 2   Product        397 non-null    str
 3   Standard Cost  397 non-null    float64
 4   Color          341 non-null    str
 5   List Price     397 non-null    float64
 6   Model          397 non-null    str
 7   Subcategory    397 non-null    str
 8   Category       397 non-null    str
dtypes: float64(2), int64(1), str(6)
memory usage: 28.0 KB

In [34]:
# Vérification de la présence de valeurs nulles
for df in dataframes_with_empty_cell:
    # On regarde les colonnes avec des valeurs manquantes pour les df trouvés
    print(dataframes[df].isna().sum())

SalesOrderLineKey          0
ResellerKey                0
CustomerKey                0
ProductKey                 0
OrderDateKey               0
DueDateKey                 0
ShipDateKey                0
SalesTerritoryKey          0
Order Quantity             0
Unit Price                 0
Extended Amount            0
Unit Price Discount Pct    0
Product Standard Cost      0
Total Product Cost         0
Sales Amount               0
dtype: int64
ProductKey        0
SKU               0
Product           0
Standard Cost     0
Color            56
List Price        0
Model             0
Subcategory       0
Category          0
dtype: int64

> Vérifiez dans les ventes que le total des ventes est correct, notamment lorsque la valeur de remise (discount) est non nulle.

In [35]:
df_sales = dataframes['sales']
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 121253 entries, 0 to 121252
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   SalesOrderLineKey        121253 non-null  int64
 1   ResellerKey              121253 non-null  int64
 2   CustomerKey              121253 non-null  int64
 3   ProductKey               121253 non-null  int64
 4   OrderDateKey             121253 non-null  int64
 5   DueDateKey               121253 non-null  int64
 6   ShipDateKey              121253 non-null  Int64
 7   SalesTerritoryKey        121253 non-null  int64
 8   Order Quantity           121253 non-null  int64
 9   Unit Price               121253 non-null  float64
 10  Extended Amount          121253 non-null  float64
 11  Unit Price Discount Pct  121253 non-null  int64
 12  Product Standard Cost    121253 non-null  float64
 13  Total Product Cost       121253 non-null  float64
 14  Sales Amount             121253 non-null  float64
dtypes: Int64(1), float64(5), int64(9)
memory usage: 14.0 MB

On nous demande ici de vérifier dans les ventes que le total des ventes est correct surtout si la valeur de remise est non null.
Tout d'abord, nous vérifions que le colonne n'a pas de remise null et nous allons effectuer les différents contrôles par la suite.

In [ ]:
# On vérifie que la colonne n'a pas de remise nulle
df_discount_not_null = df_sales["Unit Price Discount Pct"].isna()

# On vérifie que toutes les lignes ont une remise définie
df_discount_not_null.sum()

# np.int64(0) -> Aucune valeur nulle trouvée dans cette colonne

np.int64(0)

### Contrôle du montant avant remise

In [ ]:
# On fait une copie sur le DataFrame actuel pour faire les calculs souhaités sans modifier le DataFrame de base
df_sales_copy = df_sales.copy()

tolerance = 0.01 # Nous tolérons ici que 1 centime d'écart max

# Contrôle du montant avant remise
df_sales_copy["Expected Extended Amount"] = df_sales_copy["Order Quantity"] * df_sales_copy["Unit Price"]
df_sales_copy["Valid Extended Amount"] = np.isclose(
    df_sales_copy["Extended Amount"],
    df_sales_copy["Expected Extended Amount"],
    atol=tolerance
)

# Si True dans Valid Extended Amount, la valeur attendue est correcte

df_sales_copy

        SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  DueDateKey  ...  Unit Price Discount Pct  Product Standard Cost  Total Product Cost  Sales Amount  Expected Extended Amount  Valid Extended Amount
0                43659001          676           -1         349      20170702    20170712  ...                    0                1898.0944             1898.0944      2024.994             2024.994                      True
1                43659002          676           -1         350      20170702    20170712  ...                    0                1898.0944             5694.2832      6074.982             6074.982                      True
2                43659003          676           -1         351      20170702    20170712  ...                    0                1898.0944             1898.0944      2024.994             2024.994                      True
3                43659004          676           -1         344      20170702    20170712  ...                    0                1912.1544             1912.1544      2039.994             2039.994                      True
4                43659005          676           -1         345      20170702    20170712  ...                    0                1912.1544             1912.1544      2039.994             2039.994                      True
...                   ...          ...          ...         ...           ...         ...  ...                  ...                      ...                   ...           ...                  ...                       ...
121248           75122001           -1        15868         485      20200615    20200625  ...                    0                   8.2205                8.2205        21.980               21.980                      True
121249           75122002           -1        15868         225      20200615    20200625  ...                    0                   6.9223                6.9223         8.990                8.990                      True
121250           75123001           -1        18759         485      20200615    20200625  ...                    0                   8.2205                8.2205        21.980               21.980                      True
121251           75123002           -1        18759         486      20200615    20200625  ...                    0                  59.4660               59.4660       159.000              159.000                      True
121252           75123003           -1        18759         225      20200615    20200625  ...                    0                   6.9223                6.9223         8.990                8.990                      True

[121253 rows x 17 columns]

### Contrôle du montant après remise

In [46]:
# Contrôle du montant avant remise
df_sales_copy["Expected Sales Amount"] = df_sales_copy["Order Quantity"] * df_sales_copy["Unit Price"] * (1 - df_sales_copy["Unit Price Discount Pct"] / 100)
df_sales_copy["Valid Sales Amount"] = np.isclose(
    df_sales_copy["Sales Amount"],
    df_sales_copy["Expected Sales Amount"],
    atol=tolerance
)

# Si True dans Valid Sales Amount, la valeur attendue est correcte

df_sales_copy

        SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  DueDateKey  ...  Total Product Cost  Sales Amount  Expected Extended Amount  Valid Extended Amount  Expected Sales Amount  Valid Sales Amount
0                43659001          676           -1         349      20170702    20170712  ...           1898.0944      2024.994             2024.994                      True               2024.994                  True
1                43659002          676           -1         350      20170702    20170712  ...           5694.2832      6074.982             6074.982                      True               6074.982                  True
2                43659003          676           -1         351      20170702    20170712  ...           1898.0944      2024.994             2024.994                      True               2024.994                  True
3                43659004          676           -1         344      20170702    20170712  ...           1912.1544      2039.994             2039.994                      True               2039.994                  True
4                43659005          676           -1         345      20170702    20170712  ...           1912.1544      2039.994             2039.994                      True               2039.994                  True
...                   ...          ...          ...         ...           ...         ...  ...                 ...           ...                  ...                       ...                    ...                   ...
121248           75122001           -1        15868         485      20200615    20200625  ...              8.2205        21.980               21.980                      True                 21.980                  True
121249           75122002           -1        15868         225      20200615    20200625  ...              6.9223         8.990                8.990                      True                  8.990                  True
121250           75123001           -1        18759         485      20200615    20200625  ...              8.2205        21.980               21.980                      True                 21.980                  True
121251           75123002           -1        18759         486      20200615    20200625  ...             59.4660       159.000              159.000                      True                159.000                  True
121252           75123003           -1        18759         225      20200615    20200625  ...              6.9223         8.990                8.990                      True                  8.990                  True

[121253 rows x 19 columns]

### Contrôle du coût total

In [47]:
# Contrôle du coût total
df_sales_copy["Expected Total Product Cost"] = df_sales_copy["Order Quantity"] * df_sales_copy["Product Standard Cost"]
df_sales_copy["Valid Total Product Cost"] = np.isclose(
    df_sales_copy["Total Product Cost"],
    df_sales_copy["Expected Total Product Cost"],
    atol=tolerance
)

# Si True dans Valid Total Product Cost, la valeur attendue est correcte

df_sales_copy

,SalesOrderLineKey,ResellerKey,CustomerKey,ProductKey,OrderDateKey,DueDateKey,...,Expected Extended Amount,Valid Extended Amount,Expected Sales Amount,Valid Sales Amount,Expected Total Product Cost,Valid Total Product Cost
0,43659001,676,-1,349,20170702,20170712,...,2024.994,True,2024.994,True,1898.0944,True
1,43659002,676,-1,350,20170702,20170712,...,6074.982,True,6074.982,True,5694.2832,True
2,43659003,676,-1,351,20170702,20170712,...,2024.994,True,2024.994,True,1898.0944,True
3,43659004,676,-1,344,20170702,20170712,...,2039.994,True,2039.994,True,1912.1544,True
4,43659005,676,-1,345,20170702,20170712,...,2039.994,True,2039.994,True,1912.1544,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121248,75122001,-1,15868,485,20200615,20200625,...,21.980,True,21.980,True,8.2205,True
121249,75122002,-1,15868,225,20200615,20200625,...,8.990,True,8.990,True,6.9223,True
121250,75123001,-1,18759,485,20200615,20200625,...,21.980,True,21.980,True,8.2205,True
121251,75123002,-1,18759,486,20200615,20200625,...,159.000,True,159.000,True,59.4660,True
121252,75123003,-1,18759,225,20200615,20200625,...,8.990,True,8.990,True,6.9223,True

### Vérification globale

In [53]:
# On affiche les lignes problématiques

erreurs = df_sales_copy.loc[
    ~(df_sales_copy["Valid Extended Amount"]
      & df_sales_copy["Valid Sales Amount"]
      & df_sales_copy["Valid Total Product Cost"]      
      )
]

print(f"Nombre de lignes incorrectes : {len(erreurs)}")

# erreurs[["Order Quantity", "Unit Price", "Extended Amount", "Unit Price Discount Pct", "Sales Amount", "Valid Extended Amount", "Valid Sales Amount", "Valid Total Product Cost"]]
erreurs[["Sales Amount",  "Unit Price Discount Pct", "Expected Sales Amount", "Valid Sales Amount"]]

Nombre de lignes incorrectes : 3282

       Sales Amount  Unit Price Discount Pct  Expected Sales Amount  Valid Sales Amount
656      23190.6518                    0               23663.9304                 False
658      24938.4761                    0               25447.4246                 False
713         63.8733                    0                  65.1768                 False
734        104.2388                    0                 109.7250                 False
769      27055.7604                    0               27607.9188                 False
...             ...                  ...                      ...                   ...
60808       54.2254                    0                  55.3320                 False
60821      135.5976                    0                 225.9960                 False
60822      135.5976                    0                 225.9960                 False
60835      548.5466                    0                 577.4175                 False
60854      203.3964                    0                 338.9940                 False

[3282 rows x 4 columns]

Nous observons que 3282 lignes semblent ne pas avoir le résultat attendu pour le Sales Amount

> Créez une colonne  Price ratio calculant le multiplicateur entre le prix affiché et le coût du produit.

Ici le ratio correspond au rapport entre le prix de vente unitaire et le coût unitaire du produit.
Un produit coûtant 100€ et vendu à 150€ a son ratio égal à 1.5

In [54]:
df_sales_copy["Price ratio"] = (
    df_sales_copy["Unit Price"]
    .div(df_sales_copy["Product Standard Cost"].replace(0, np.nan))
    .round(2)
)

df_sales_copy.head(10)

   SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  DueDateKey  ...  Valid Extended Amount  Expected Sales Amount  Valid Sales Amount  Expected Total Product Cost  Valid Total Product Cost  Price ratio
0           43659001          676           -1         349      20170702    20170712  ...                 True              2024.9940                  True            1898.0944                         True              1.07
1           43659002          676           -1         350      20170702    20170712  ...                 True              6074.9820                  True            5694.2832                         True              1.07
2           43659003          676           -1         351      20170702    20170712  ...                 True              2024.9940                  True            1898.0944                         True              1.07
3           43659004          676           -1         344      20170702    20170712  ...                 True              2039.9940                  True            1912.1544                         True              1.07
4           43659005          676           -1         345      20170702    20170712  ...                 True              2039.9940                  True            1912.1544                         True              1.07
5           43659006          676           -1         346      20170702    20170712  ...                 True              4079.9880                  True            3824.3088                         True              1.07
6           43659007          676           -1         347      20170702    20170712  ...                 True              2039.9940                  True            1912.1544                         True              1.07
7           43659008          676           -1         229      20170702    20170712  ...                 True                86.5212                  True              95.1732                         True              0.91
8           43659009          676           -1         235      20170702    20170712  ...                 True                28.8404                  True              31.7244                         True              0.91
9           43659010          676           -1         218      20170702    20170712  ...                 True                34.2000                  True              20.3778                         True              1.68

[10 rows x 22 columns]